// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ioid.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ioid_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ioid_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ioid_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ioid_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ioid_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

enum IOID : int {
  IOID_REGISTER_REQ = 0,
  IOID_REGISTER_RSP = 1,
  IOID_AUTH_REQ = 2,
  IOID_AUTH_RSP = 3,
  IOID_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  IOID_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool IOID_IsValid(int value);
constexpr IOID IOID_MIN = IOID_REGISTER_REQ;
constexpr IOID IOID_MAX = IOID_AUTH_RSP;
constexpr int IOID_ARRAYSIZE = IOID_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* IOID_descriptor();
template<typename T>
inline const std::string& IOID_Name(T enum_t_value) {
  static_assert(::std::is_same<T, IOID>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function IOID_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    IOID_descriptor(), enum_t_value);
}
inline bool IOID_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, IOID* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<IOID>(
    IOID_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::IOID> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::IOID>() {
  return ::IOID_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ioid_2eproto
