[Logger]
level = 0
file_name = "logs/dbsrv.log"
spsc_blk_num = 524288	# 一个blk为64bytes 512k * 64bytes = 32MB

[Server]
pp_alloc_num = 1024
ps_alloc_num = 1024
spsc_blk_num = 524288

[Timer]
tp_alloc_num = 1024
ts_alloc_num = 1024

[DBSrv]
id = 1
interval = 1
ip = "127.0.0.1"

[LBSrv]
id = 1
ip = "127.0.0.1"
port = 6667
timeout = 3000

[Proxy]
timeout = 3000

[MySql]
db_name = ""
ip = "127.0.0.1"
username = "root"
password = "123456"
